### ISSUE TITLE
Move `AjaxWith`/`Ajax` from Core

### ISSUE THREAD

**Issue by btamas2000** [dotnet-websharper/jquery#5]
Methods to move:
    - In `WebSharper.Sitelets.Router` :
          - `AjaxWith`
          - `Ajax`

**Comment by granicz** [comment]
Expose these as extension members under the same FQN.

**Comment by btamas2000** [comment]
Solution in https://github.com/dotnet-websharper/jquery/commit/19cf50e881568332a6bfdc5170308deec275af93
