### ISSUE TITLE
When trying to execute build.cmd...

### ISSUE THREAD

**Issue by ingted** [dotnet-websharper/jquery#8]
![image](https://user-images.githubusercontent.com/4289161/212444342-db631fed-b3d4-477a-835c-16f2dacca536.png)

**Comment by ingted** [comment]
Maybe caused by github?!
![image](https://user-images.githubusercontent.com/4289161/212444495-3c082690-f1c2-45fd-a96e-870be981eea8.png)

**Comment by ingted** [comment]
I removed all paket stuff and added 
```
<WebSharperProject>binding</WebSharperProject>
```
and change to
```
"project": "binding"
```
then it builds 0_0  lol

**Comment by ingted** [comment]
However only C# project could recognize the Resource.JQuery

![image](https://user-images.githubusercontent.com/4289161/212447408-86137947-7aba-40f4-97a7-9fcd8f2d1203.png)

But not F# project...

![image](https://user-images.githubusercontent.com/4289161/212447417-a2db9f5c-7d68-4353-881e-1c19e6429036.png)

![image](https://user-images.githubusercontent.com/4289161/212447433-6c0a780e-def1-4a5c-862e-3c0da01236a1.png)

Here is my repo:

https://github.com/ingted/WebSharper.JQuery

**Comment by ingted** [comment]
Oops... it fails to work again in F# project...

![image](https://user-images.githubusercontent.com/4289161/212457176-3f850a43-a1d7-4bb1-b348-aeb05930813c.png)

**Comment by ingted** [comment]
Finally I remembered that we could not put the project in the same solution.... Once I removed the project from the solution after building successfully. All references become normal.

**Comment by granicz** [comment]
@ingted Local builds use the WebSharper GitHub feed, so just configure that - there is work-in-progress (WIP) doc page that describes the steps at https://docs.websharper.com/basics/nuget/#configuring-the-websharper-developer-feed
